INSERT INTO PRODUCT (NAME, PRICE, QUANTITY) VALUES ('Mother board', 199.99, 15);
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY) VALUES ('Key board', 121.5, 12);
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY) VALUES ('Speaker', 203.5, 15);
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY) VALUES ('Monitor', 249.99, 10);
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY) VALUES ('Mouse', 79.99, 21);
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY) VALUES ('Graphic Card', 499.99, 9);

